### ISSUE TITLE
Regard

### ISSUE THREAD

**Issue by gauravmunjal13** [medalab-dladpcfncp/alpha#1]
Dear,

I am trying to reproduce your work, however, the following line gives the error:
`from data_loader.create_boxdata import finecut_to_thickcut`
In the data_loader, there is no create_boxdata file. 

Thank you! Looking forward to your response!

**Comment by medalab-dladpcfncp** [comment]
Hi, 

Thank you for mentioning it! We plan to update the code with this issue along with other features, which will release in a couple of weeks.

**Comment by medalab-dladpcfncp** [comment]
Hi, 

We just added the `finecut_to_thickcut` part. If there's any other issue, please kindly let us know. Thank you!
